import {emailRules, jsonRuleOrNull, requiredRules} from '@/helpers/validate-rules';

export default {
    rules: {
        title: 'Rules',
        model: {
            name: null,
            rule_date_from: null,
            rule_date_to: null,
            rule_affiliate_network: null,
            rule_country: '[]',
            rule_days: '[]',
        },
        headers: [
            {text: 'ID', value: 'id'},
            {text: 'Name', value: 'name'},
            {text: 'Date From', value: 'rule_date_from'},
            {text: 'Date To', value: 'rule_date_to'},
            {text: 'Affiliate Network', value: 'rule_affiliate_network'},
            {text: 'Country', value: 'rule_country'},
            {text: 'Days', value: 'rule_days'},
        ],
        fields: [
            {name: 'name', label: 'Name', type: 'string'},
            {name: 'rule_date_from', label: 'Date From', type: 'time-picker'},
            {name: 'rule_date_to', label: 'Date To', type: 'time-picker'},
            {name: 'rule_affiliate_network', label: 'Affiliate Network', type: 'string'},
            {name: 'rule_country', label: 'Country', type: 'country-select', cols:6},
            {name: 'rule_days', label: 'Days', type: 'day-select', cols:6},
        ],
    },
    'rule-boxes': {
        title: 'Rule Boxes',
        model: {
            rule_affiliate_network: null,
            rule_country: '[]',
            rule_language: '[]',
            rule_offerName: null,
            rule_box: null,
            workspace: null,
        },
        headers: [
            {text: 'ID', value: 'id'},
            {text: 'Affiliate Network', value: 'rule_affiliate_network'},
            {text: 'Country', value: 'rule_country'},
            {text: 'Language', value: 'rule_language'},
            {text: 'Offer Name', value: 'rule_offerName'},
            {text: 'Rule Box', value: 'rule_box'},
            {text: 'Workspace', value: 'workspace'},
        ],
        fields: [
            {name: 'rule_affiliate_network', label: 'Affiliate Network', type: 'string', rule: requiredRules, cols: 3}, //JSOn
            {name: 'rule_offerName', label: 'Offer Name', type: 'string'},
            {name: 'rule_box', label: 'Rule Box', type: 'number', rule: requiredRules, cols: 3},
            {name: 'workspace', label: 'Workspace', type: 'number', rule: requiredRules, cols: 3},
            {name: 'rule_country', label: 'Country', type: 'country-select', cols:6},
            {name: 'rule_language', label: 'Language', type: 'language-select', cols:6},
        ],
    },
    partners: {
        title: 'Partners',
        model: {
            name: null,
            aff_name: null,
            type: null,
            vertical: null,
            workspace: null,
        },
        headers: [
            {text: 'ID', value: 'id'},
            {text: 'Name', value: 'name'},
            {text: 'AFF Name', value: 'aff_name'},
            {text: 'Type', value: 'type'},
            {text: 'Vertical', value: 'vertical'},
            {text: 'Workspace', value: 'workspace'},
        ],
        fields: [
            {name: 'name', label: 'Name', type: 'string', rule: requiredRules, cols: 3},
            {name: 'aff_name', label: 'AFF Name', type: 'string', rule: [], cols: 3},
            {name: 'type', label: 'Type', type: 'string', rule: [], cols: 3},
            {name: 'vertical', label: 'Vertical', type: 'string', rule: [], cols: 3},
            {name: 'workspace', label: 'Workspace', type: 'number', rule: requiredRules, cols: 3},
        ],
    },
    leads: {
        title: 'Leads',
        serverRender: true,
        filter: [
            {text: 'Workspace', value: 'workspace', width: "150px"},
        ],
        model: {
            first_name: null,
            last_name: null,
            phone_code: null,
            phone: null,
            email: null,
            password: null,
            date: null,
            ip: null,
            country: null,
            countryISO: null,
            language: null,
            platform: null,
            browser: null,
            partner: null,
            clickId: null,
            campaign_id: null,
            offerName: null,
            offerUrl: "",
            landingUrl: "",
            landingData: "{\"landing_to_offer_button_id\":\"\"}",
            traffic_source: null,
            traffic_source_account: "",
            traffic_source_account_creative: null,
            description: null,
            write_base: null,
            type: null,
            workspace: null
        },
        headers: [
            {text: 'Name', value: 'first_name', width: "150px"},
            {text: 'Last name', value: 'last_name', width: "150px"},
            {text: 'Phone code', value: 'phone_code', width: "150px"},
            {text: 'Phone', value: 'phone'},
            {text: 'Email', value: 'email'},
            {text: 'Country', value: 'country', width: "150px"},
            {text: 'Offer name', value: 'offerName', width: "200px"},
            {text: 'Offer url', value: 'offerUrl', width: "300px"},
            {text: 'Date', value: 'date', width: "200px"},
        ],
        fields: [
            {name: 'first_name', label: 'Name', type: 'string', rule: requiredRules},
            {name: 'last_name', label: 'Name', type: 'string', rule: requiredRules},
            {name: 'phone_code', label: 'Phone code', type: 'string', rule: requiredRules},
            {name: 'phone', label: 'Phone', type: 'string', rule: requiredRules},
            {name: 'email', label: 'Email', type: 'string', rule: emailRules},
            {name: 'country', label: 'Country', type: 'string', rule: requiredRules},
            {name: 'countryISO', label: 'country ISO', type: 'string', rule: requiredRules},
            {name: 'ip', label: 'IP', type: 'string', rule: requiredRules},
            {name: 'language', label: 'Language', type: 'string'},
            {name: 'platform', label: 'Platform', type: 'string'},
            {name: 'password', label: 'Password', type: 'string', rule: requiredRules},
            {name: 'browser', label: 'Browser', type: 'string'},
            {name: 'clickId', label: 'Click ID', type: 'string', rule: requiredRules},
            {name: 'campaign_id', label: 'Campaign id', type: 'string'},
            {name: 'offerName', label: 'offer name', type: 'string', rule: requiredRules},
            {name: 'offerUrl', label: 'Offer url', type: 'string', rule: requiredRules},
            {name: 'landingUrl', label: 'Landing Url', type: 'string'},
            {name: 'landingData', label: 'Landing Data', type: 'string', rule: requiredRules},
            {name: 'traffic_source', label: 'Traffic Source', type: 'string', rule: requiredRules},
            {name: 'traffic_source_account', label: 'Traffic Source Account', type: 'string', rule: requiredRules},
            {name: 'traffic_source_account_creative', label: 'Traffic Source Creative', type: 'string', rule: requiredRules},
            {name: 'write_base', label: 'Write base', type: 'string'},
            {name: 'type', label: 'Type', type: 'string', rule: requiredRules},
            {name: 'workspace', label: 'Workspace', type: 'number', rule: requiredRules},
            {name: 'date', label: 'Date', type: 'datetime', rule: requiredRules},
            {name: 'partner', label: 'Partner', type: 'textarea'},
            {name: 'description', label: 'Description', type: 'textarea'},

        ],
    },
    conversions: {
        title: 'Conversions',
        serverRender: true,
        model: {
            affiliate_network: null,
            type: null,
            traffic_type: null,
            payout: 0,
            clickId: null,
            workspace: null,
            datetime: null
        },
        headers: [
            {text: 'ID', value: 'id'},
            {text: 'Affiliate Network', value: 'affiliate_network'},
            {text: 'Click ID', value: 'clickId'},
            {text: 'Payout', value: 'payout'},
            {text: 'Type', value: 'type'},
            {text: 'Traffic type', value: 'traffic_type'},
            {text: 'Workspace', value: 'workspace'},
            {text: 'Date', value: 'datetime'},
        ],
        fields: [
            {name: 'affiliate_network', label: 'Affiliate Network', type: 'string', rule: requiredRules},
            {name: 'type', label: 'Type', type: 'string', rule: requiredRules},
            {name: 'traffic_type', label: 'Traffic type', type: 'string'},
            {name: 'clickId', label: 'Click ID', type: 'string', rule: requiredRules},
            {name: 'payout', label: 'Payout', type: 'number', rule: requiredRules},
            {name: 'workspace', label: 'Workspace', type: 'number', rule: requiredRules},
            {name: 'datetime', label: 'Date', type: 'datetime', rule: requiredRules},
        ],
    },
    users: {
        title: 'User',
        model: {
            login: null,
            password: null,
            email: null,
            team: '[]',
            allTeam: '[]',
            status: null,
        },
        headers: [
            {text: 'Login', value: 'login'},
            {text: 'Email', value: 'email'},
            {text: 'Team', value: 'team'},
            {text: 'All Team', value: 'allTeam'},
            {text: 'Status', value: 'status'},
        ],
        fields: [
            {name: 'login', label: 'Login', type: 'string', rule: requiredRules},
            {name: 'password', label: 'Password', type: 'string'},
            {name: 'email', label: 'Email type', type: 'string', rule: emailRules},
            {name: 'team', label: 'Team', type: 'textarea', rule: jsonRuleOrNull},
            {name: 'allTeam', label: 'All Team', type: 'textarea', rule: jsonRuleOrNull},
            {name: 'status', label: 'Status', type: 'string', rule: requiredRules},
        ],
    },
    'affiliate-histories': {
        title: 'Affiliate history',
        serverRender: true,
        model: {
            lead_click_id: null,
            lead_status: null,
            affiliate_name: null,
            aff_lead_id: null,
            send_with_autologin: null,
            send_with_ip: null,
            result_autologin: null,
            autologin_screenshot: null,
            response: '{}',
            traffic_type: null,
            country: null,
            countryISO: null,
            traffic_source: null,
            status: null,
            workspace: null,
            datetime: null
        },
        headers: [
            {text: 'Lead Click ID', value: 'lead_click_id'},
            {text: 'Lead Status', value: 'lead_status'},
            {text: 'Affiliate Name', value: 'affiliate_name'},
            {text: 'Lead ID', value: 'aff_lead_id'},
            {text: 'Traffic Type', value: 'traffic_type'},
            {text: 'Country', value: 'country'},
            {text: 'Traffic Source', value: 'traffic_source'},
            {text: 'Status', value: 'status'},
            {text: 'Workspace', value: 'workspace'},
            {text: 'Date', value: 'datetime', width: "150px"},
        ],
        fields: [
            {name: 'lead_click_id', label: 'Lead Click ID', type: 'string', rule: requiredRules},
            {name: 'lead_status', label: 'Lead Status', type: 'string'},
            {name: 'affiliate_name', label: 'Affiliate Name', type: 'string', rule: requiredRules},
            {name: 'aff_lead_id', label: 'Affiliate Lead_ ID', type: 'string'},
            {name: 'send_with_autologin', label: 'Send With Autologin', type: 'string'},
            {name: 'send_with_ip', label: 'Send With IP', type: 'string'},
            {name: 'result_autologin', label: 'Result Autologin', type: 'string'},
            {name: 'autologin_screenshot', label: 'Autologin Screenshot', type: 'string'},
            {name: 'response', label: 'Response', type: 'textarea', cols: 6, rule: jsonRuleOrNull},
            {name: 'traffic_type', label: 'Traffic Type', type: 'string'},
            {name: 'country', label: 'Country', type: 'string',  rule: requiredRules},
            {name: 'countryISO', label: 'Country ISO', type: 'string', rule: requiredRules},
            {name: 'traffic_source', label: 'Traffic Source', type: 'string', rule: requiredRules},
            {name: 'status', label: 'Status', type: 'string', rule: requiredRules},
            {name: 'workspace', label: 'Workspace', type: 'number', rule: requiredRules},
            {name: 'datetime', label: 'Date', type: 'datetime', rule: requiredRules},
        ],
    },
}
